backend:
  name: git-gateway
  branch: master
collections:
  - name: "content"
    label: "Content"
    folder: "content"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Category",
          name: "category",
          widget: "string",
          multiple: false,
          options: ["tutorial", "off-topic", "psws"],
        }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
publish_mode: editorial_workflow
media_folder: "public/images"
public_folder: "/images"
